# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

target 'JustPassMeReactNative' do
  pod 'justpass-me'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JustPassMeReactNative

end
